
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="color-scheme" content="light dark">
    <title>PEP 654 – Exception Groups and except* | peps.python.org</title>
    <link rel="shortcut icon" href="../_static/py.png">
    <link rel="canonical" href="https://peps.python.org/pep-0654/">
    <link rel="stylesheet" href="../_static/style.css" type="text/css">
    <link rel="stylesheet" href="../_static/mq.css" type="text/css">
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" media="(prefers-color-scheme: light)" id="pyg-light">
    <link rel="stylesheet" href="../_static/pygments_dark.css" type="text/css" media="(prefers-color-scheme: dark)" id="pyg-dark">
    <link rel="alternate" type="application/rss+xml" title="Latest PEPs" href="https://peps.python.org/peps.rss">
    <meta property="og:title" content='PEP 654 – Exception Groups and except* | peps.python.org'>
    <meta property="og:description" content="This document proposes language extensions that allow programs to raise and handle multiple unrelated exceptions simultaneously:">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://peps.python.org/pep-0654/">
    <meta property="og:site_name" content="Python Enhancement Proposals (PEPs)">
    <meta property="og:image" content="https://peps.python.org/_static/og-image.png">
    <meta property="og:image:alt" content="Python PEPs">
    <meta property="og:image:width" content="200">
    <meta property="og:image:height" content="200">
    <meta name="description" content="This document proposes language extensions that allow programs to raise and handle multiple unrelated exceptions simultaneously:">
    <meta name="theme-color" content="#3776ab">
</head>
<body>
    
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="svg-sun-half" viewBox="0 0 24 24" pointer-events="all">
    <title>Following system colour scheme</title>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="12" cy="12" r="9"></circle>
      <path d="M12 3v18m0-12l4.65-4.65M12 14.3l7.37-7.37M12 19.6l8.85-8.85"></path>
    </svg>
  </symbol>
  <symbol id="svg-moon" viewBox="0 0 24 24" pointer-events="all">
    <title>Selected dark colour scheme</title>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"></path>
    </svg>
  </symbol>
  <symbol id="svg-sun" viewBox="0 0 24 24" pointer-events="all">
    <title>Selected light colour scheme</title>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="12" cy="12" r="5"></circle>
      <line x1="12" y1="1" x2="12" y2="3"></line>
      <line x1="12" y1="21" x2="12" y2="23"></line>
      <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
      <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
      <line x1="1" y1="12" x2="3" y2="12"></line>
      <line x1="21" y1="12" x2="23" y2="12"></line>
      <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
      <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
    </svg>
  </symbol>
</svg>
    <script>

        document.documentElement.dataset.colour_scheme = localStorage.getItem("colour_scheme") || "auto"
    </script>
    <section id="pep-page-section">
        <header>
            <h1>Python Enhancement Proposals</h1>
            <ul class="breadcrumbs">
                <li><a href="https://www.python.org/" title="The Python Programming Language">Python</a> &raquo; </li>
                <li><a href="../pep-0000/">PEP Index</a> &raquo; </li>
                <li>PEP 654</li>
            </ul>
            <button id="colour-scheme-cycler" onClick="setColourScheme(nextColourScheme())">
                <svg aria-hidden="true" class="colour-scheme-icon-when-auto"><use href="#svg-sun-half"></use></svg>
                <svg aria-hidden="true" class="colour-scheme-icon-when-dark"><use href="#svg-moon"></use></svg>
                <svg aria-hidden="true" class="colour-scheme-icon-when-light"><use href="#svg-sun"></use></svg>
                <span class="visually-hidden">Toggle light / dark / auto colour theme</span>
            </button>
        </header>
        <article>
            <section id="pep-content">
<h1 class="page-title">PEP 654 – Exception Groups and except*</h1>
<dl class="rfc2822 field-list simple">
<dt class="field-odd">Author<span class="colon">:</span></dt>
<dd class="field-odd">Irit Katriel &lt;irit&#32;&#97;t&#32;python.org&gt;,
Yury Selivanov &lt;yury&#32;&#97;t&#32;edgedb.com&gt;,
Guido van Rossum &lt;guido&#32;&#97;t&#32;python.org&gt;</dd>
<dt class="field-even">Discussions-To<span class="colon">:</span></dt>
<dd class="field-even"><a class="reference external" href="https://discuss.python.org/t/accepting-pep-654-exception-groups-and-except/10813">Discourse thread</a></dd>
<dt class="field-odd">Status<span class="colon">:</span></dt>
<dd class="field-odd"><abbr title="Accepted and implementation complete, or no longer active">Final</abbr></dd>
<dt class="field-even">Type<span class="colon">:</span></dt>
<dd class="field-even"><abbr title="Normative PEP with a new feature for Python, implementation change for CPython or interoperability standard for the ecosystem">Standards Track</abbr></dd>
<dt class="field-odd">Created<span class="colon">:</span></dt>
<dd class="field-odd">22-Feb-2021</dd>
<dt class="field-even">Python-Version<span class="colon">:</span></dt>
<dd class="field-even">3.11</dd>
<dt class="field-odd">Post-History<span class="colon">:</span></dt>
<dd class="field-odd"><a class="reference external" href="https://mail.python.org/archives/list/python-dev&#64;python.org/thread/L5Q27DVKOKZCDNCAWRIQVOZ5DZCZHLRM/" title="Python-Dev thread">22-Feb-2021</a>,
<a class="reference external" href="https://mail.python.org/archives/list/python-dev&#64;python.org/thread/MQ2UCSQ2ZC4FIGT7KSVI6BJA4FCXSOCL/" title="Python-Dev thread">20-Mar-2021</a>,
<a class="reference external" href="https://mail.python.org/archives/list/python-dev&#64;python.org/thread/4B256YKUPW5P2M44GG5H6FBL3PSV6ODP/" title="Python-Dev thread">03-Oct-2021</a></dd>
<dt class="field-even">Resolution<span class="colon">:</span></dt>
<dd class="field-even"><a class="reference external" href="https://discuss.python.org/t/accepting-pep-654-exception-groups-and-except/10813/1">Discourse message</a></dd>
</dl>
<hr class="docutils" />
<section id="contents">
<details><summary>Table of Contents</summary><ul class="simple">
<li><a class="reference internal" href="#abstract">Abstract</a></li>
<li><a class="reference internal" href="#motivation">Motivation</a></li>
<li><a class="reference internal" href="#rationale">Rationale</a></li>
<li><a class="reference internal" href="#specification">Specification</a><ul>
<li><a class="reference internal" href="#exceptiongroup-and-baseexceptiongroup">ExceptionGroup and BaseExceptionGroup</a><ul>
<li><a class="reference internal" href="#subclassing-exception-groups">Subclassing Exception Groups</a></li>
<li><a class="reference internal" href="#the-traceback-of-an-exception-group">The Traceback of an Exception Group</a></li>
<li><a class="reference internal" href="#handling-exception-groups">Handling Exception Groups</a></li>
</ul>
</li>
<li><a class="reference internal" href="#except">except*</a><ul>
<li><a class="reference internal" href="#recursive-matching">Recursive Matching</a></li>
<li><a class="reference internal" href="#unmatched-exceptions">Unmatched Exceptions</a></li>
<li><a class="reference internal" href="#naked-exceptions">Naked Exceptions</a></li>
<li><a class="reference internal" href="#raising-exceptions-in-an-except-block">Raising exceptions in an <code class="docutils literal notranslate"><span class="pre">except*</span></code> block</a></li>
<li><a class="reference internal" href="#chaining">Chaining</a></li>
<li><a class="reference internal" href="#raising-new-exceptions">Raising New Exceptions</a></li>
<li><a class="reference internal" href="#caught-exception-objects">Caught Exception Objects</a></li>
<li><a class="reference internal" href="#forbidden-combinations">Forbidden Combinations</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="reference internal" href="#backwards-compatibility">Backwards Compatibility</a></li>
<li><a class="reference internal" href="#how-to-teach-this">How to Teach This</a></li>
<li><a class="reference internal" href="#reference-implementation">Reference Implementation</a></li>
<li><a class="reference internal" href="#rejected-ideas">Rejected Ideas</a><ul>
<li><a class="reference internal" href="#make-exception-groups-iterable">Make Exception Groups Iterable</a></li>
<li><a class="reference internal" href="#make-exceptiongroup-extend-baseexception">Make <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> Extend <code class="docutils literal notranslate"><span class="pre">BaseException</span></code></a></li>
<li><a class="reference internal" href="#make-it-impossible-to-wrap-baseexceptions-in-an-exception-group">Make it Impossible to Wrap <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code> in an Exception Group</a></li>
<li><a class="reference internal" href="#traceback-representation">Traceback Representation</a></li>
<li><a class="reference internal" href="#extend-except-to-handle-exception-groups">Extend <code class="docutils literal notranslate"><span class="pre">except</span></code> to Handle Exception Groups</a></li>
<li><a class="reference internal" href="#a-new-except-alternative">A New <code class="docutils literal notranslate"><span class="pre">except</span></code> Alternative</a></li>
<li><a class="reference internal" href="#applying-an-except-clause-on-one-exception-at-a-time">Applying an <code class="docutils literal notranslate"><span class="pre">except*</span></code> Clause on One Exception at a Time</a></li>
<li><a class="reference internal" href="#not-matching-naked-exceptions-in-except">Not Matching Naked Exceptions in <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></li>
<li><a class="reference internal" href="#allow-mixing-except-and-except-in-the-same-try">Allow mixing <code class="docutils literal notranslate"><span class="pre">except:</span></code> and <code class="docutils literal notranslate"><span class="pre">except*:</span></code> in the same <code class="docutils literal notranslate"><span class="pre">try</span></code></a></li>
<li><a class="reference internal" href="#try-instead-of-except"><code class="docutils literal notranslate"><span class="pre">try*</span></code> instead of <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></li>
<li><a class="reference internal" href="#alternative-syntax-options">Alternative syntax options</a></li>
</ul>
</li>
<li><a class="reference internal" href="#programming-without-except">Programming Without ‘except *’</a></li>
<li><a class="reference internal" href="#see-also">See Also</a></li>
<li><a class="reference internal" href="#acknowledgements">Acknowledgements</a></li>
<li><a class="reference internal" href="#acceptance">Acceptance</a></li>
<li><a class="reference internal" href="#references">References</a></li>
<li><a class="reference internal" href="#copyright">Copyright</a></li>
</ul>
</details></section>
<div class="pep-banner canonical-doc sticky-banner admonition important">
<p class="admonition-title">Important</p>
<p>This PEP is a historical document. The up-to-date, canonical documentation can now be found at <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#lib-exception-groups" title="(in Python v3.14)"><span>Exception groups</span></a> and <a class="reference external" href="https://docs.python.org/3/reference/compound_stmts.html#except-star" title="(in Python v3.14)"><span>except* clause</span></a>.</p>
<p class="close-button">×</p>
<p>See <a class="reference external" href="https://docs.python.org/3/tutorial/errors.html#tut-exception-groups" title="(in Python v3.14)"><span>Raising and Handling Multiple Unrelated Exceptions</span></a> for a user-focused tutorial.</p>
<p>See <a class="pep reference internal" href="../pep-0001/" title="PEP 1 – PEP Purpose and Guidelines">PEP 1</a> for how to propose changes.</p>
</div>
<section id="abstract">
<h2><a class="toc-backref" href="#abstract" role="doc-backlink">Abstract</a></h2>
<p>This document proposes language extensions that allow programs to raise and handle
multiple unrelated exceptions simultaneously:</p>
<ul class="simple">
<li>A new standard exception type, the <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>, which represents a
group of unrelated exceptions being propagated together.</li>
<li>A new syntax <code class="docutils literal notranslate"><span class="pre">except*</span></code> for handling <code class="docutils literal notranslate"><span class="pre">ExceptionGroups</span></code>.</li>
</ul>
</section>
<section id="motivation">
<h2><a class="toc-backref" href="#motivation" role="doc-backlink">Motivation</a></h2>
<p>The interpreter is currently able to propagate at most one exception at a
time. The chaining features introduced in <a class="pep reference internal" href="../pep-3134/" title="PEP 3134 – Exception Chaining and Embedded Tracebacks">PEP 3134</a> link together
exceptions that are related to each other as the cause or context, but
there are situations where multiple unrelated exceptions need to be propagated
together as the stack unwinds. Several real world use cases are listed below.</p>
<ul>
<li><strong>Concurrent errors</strong>. Libraries for async concurrency provide APIs to invoke
multiple tasks and return their results in aggregate. There isn’t currently
a good way for such libraries to handle situations where multiple tasks
raise exceptions. The Python standard library’s <code class="docutils literal notranslate"><span class="pre">asyncio.gather()</span></code> <a class="footnote-reference brackets" href="#id19" id="id1">[1]</a>
function provides two options: raise the first exception, or return the
exceptions in the results list.  The Trio <a class="footnote-reference brackets" href="#id20" id="id2">[2]</a>
library has a <code class="docutils literal notranslate"><span class="pre">MultiError</span></code> exception type which it raises to report a
collection of errors. Work on this PEP was initially motivated by the
difficulties in handling <code class="docutils literal notranslate"><span class="pre">MultiErrors</span></code> <a class="footnote-reference brackets" href="#id27" id="id3">[9]</a>, which are detailed in a design
document for an improved version, <code class="docutils literal notranslate"><span class="pre">MultiError2</span></code> <a class="footnote-reference brackets" href="#id21" id="id4">[3]</a>.
That document demonstrates how difficult it is to create an effective API
for reporting and handling multiple errors without the language changes we
are proposing (see also the <a class="reference internal" href="#programming-without-except">Programming Without ‘except *’</a> section.)<p>Implementing a better task spawning API in asyncio, inspired by Trio
nurseries <a class="footnote-reference brackets" href="#id31" id="id5">[13]</a>, was the main motivation for this PEP.  That work is currently
blocked on Python not having native language level support for exception
groups.</p>
</li>
<li><strong>Multiple failures when retrying an operation.</strong> The Python standard
library’s <code class="docutils literal notranslate"><span class="pre">socket.create_connection</span></code> function may attempt to connect to
different addresses, and if all attempts fail it needs to report that to the
user. It is an open issue how to aggregate these errors, particularly when
they are different (see issue 29980 <a class="footnote-reference brackets" href="#id22" id="id6">[4]</a>.)</li>
<li><strong>Multiple user callbacks fail.</strong> Python’s <code class="docutils literal notranslate"><span class="pre">atexit.register()</span></code> function
allows users to register functions that are called on system exit. If any of
them raise exceptions, only the last one is reraised, but it would be better
to reraise all of them together (see <code class="docutils literal notranslate"><span class="pre">atexit</span></code> documentation <a class="footnote-reference brackets" href="#id23" id="id7">[5]</a>.)
Similarly, the pytest library allows users to register finalizers which
are executed at teardown. If more than one of these finalizers raises an
exception, only the first is reported to the user. This can be improved with
<code class="docutils literal notranslate"><span class="pre">ExceptionGroups</span></code>, as explained in this issue by pytest developer Ran Benita
(see pytest issue 8217 <a class="footnote-reference brackets" href="#id24" id="id8">[6]</a>.)</li>
<li><strong>Multiple errors in a complex calculation.</strong> The Hypothesis library performs
automatic bug reduction (simplifying code that demonstrates a bug). In the
process it may find variations that generate different errors, and
(optionally) reports all of them (see the Hypothesis documentation <a class="footnote-reference brackets" href="#id25" id="id9">[7]</a>.)
An <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> mechanism as we are proposing here can resolve some of
the difficulties with debugging that are mentioned in the link above, and
which are due to the loss of context/cause information (communicated
by Hypothesis Core Developer Zac Hatfield-Dodds).</li>
<li><strong>Errors in wrapper code.</strong> The Python standard library’s
<code class="docutils literal notranslate"><span class="pre">tempfile.TemporaryDirectory</span></code> context manager
had an issue where an exception raised during cleanup in <code class="docutils literal notranslate"><span class="pre">__exit__</span></code>
effectively masked an exception that the user’s code raised inside the context
manager scope. While the user’s exception was chained as the context of the
cleanup error, it was not caught by the user’s except clause
(see issue 40857 <a class="footnote-reference brackets" href="#id26" id="id10">[8]</a>.)<p>The issue was resolved by making the cleanup code ignore errors, thus
sidestepping the multiple exception problem. With the features we propose
here, it would be possible for <code class="docutils literal notranslate"><span class="pre">__exit__</span></code> to raise an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
containing its own errors along with the user’s errors, and this would allow
the user to catch their own exceptions by their types.</p>
</li>
</ul>
</section>
<section id="rationale">
<h2><a class="toc-backref" href="#rationale" role="doc-backlink">Rationale</a></h2>
<p>Grouping several exceptions together can be done without changes to the
language, simply by creating a container exception type.
Trio <a class="footnote-reference brackets" href="#id20" id="id11">[2]</a> is an example of a library that has made use of this technique in its
<code class="docutils literal notranslate"><span class="pre">MultiError</span></code> <a class="footnote-reference brackets" href="#id27" id="id12">[9]</a> type. However, such an approach requires calling code to catch
the container exception type, and then to inspect it to determine the types of
errors that had occurred, extract the ones it wants to handle, and reraise the
rest. Furthermore, exceptions in Python have important information attached to
their <code class="docutils literal notranslate"><span class="pre">__traceback__</span></code>, <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> and <code class="docutils literal notranslate"><span class="pre">__context__</span></code> fields, and
designing a container type that preserves the integrity of this information
requires care; it is not as simple as collecting exceptions into a set.</p>
<p>Changes to the language are required in order to extend support for
exception groups in the style of existing exception handling mechanisms. At
the very least we would like to be able to catch an exception group only if
it contains an exception of a type that we choose to handle. Exceptions of
other types in the same group need to be automatically reraised,
otherwise it is too easy for user code to inadvertently swallow exceptions
that it is not handling.</p>
<p>We considered whether it is possible to modify the semantics of <code class="docutils literal notranslate"><span class="pre">except</span></code>
for this purpose, in a backwards-compatible manner, and found that it is not.
See the <a class="reference internal" href="#rejected-ideas">Rejected Ideas</a> section for more on this.</p>
<p>The purpose of this PEP, then, is to add the <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> builtin type
and the <code class="docutils literal notranslate"><span class="pre">except*</span></code> syntax for handling exception groups in the interpreter.
The desired semantics of <code class="docutils literal notranslate"><span class="pre">except*</span></code> are sufficiently different from the
current exception handling semantics that we are not proposing to modify the
behavior of the <code class="docutils literal notranslate"><span class="pre">except</span></code> keyword but rather to add the new <code class="docutils literal notranslate"><span class="pre">except*</span></code>
syntax.</p>
<p>Our premise is that exception groups and <code class="docutils literal notranslate"><span class="pre">except*</span></code> will be used
selectively, only when they are needed. We do not expect them to become
the default mechanism for exception handling.  The decision to raise
exception groups from a library needs to be considered carefully and
regarded as an API-breaking change. We expect that this will normally be
done by introducing a new API rather than modifying an existing one.</p>
</section>
<section id="specification">
<h2><a class="toc-backref" href="#specification" role="doc-backlink">Specification</a></h2>
<section id="exceptiongroup-and-baseexceptiongroup">
<h3><a class="toc-backref" href="#exceptiongroup-and-baseexceptiongroup" role="doc-backlink">ExceptionGroup and BaseExceptionGroup</a></h3>
<p>We propose to add two new builtin exception types:
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup(BaseException)</span></code> and
<code class="docutils literal notranslate"><span class="pre">ExceptionGroup(BaseExceptionGroup,</span> <span class="pre">Exception)</span></code>. They are assignable to
<code class="docutils literal notranslate"><span class="pre">Exception.__cause__</span></code> and <code class="docutils literal notranslate"><span class="pre">Exception.__context__</span></code>, and they can be
raised and handled as any exception with <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">ExceptionGroup(...)</span></code> and
<code class="docutils literal notranslate"><span class="pre">try:</span> <span class="pre">...</span> <span class="pre">except</span> <span class="pre">ExceptionGroup:</span> <span class="pre">...</span></code> or <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">BaseExceptionGroup(...)</span></code>
and <code class="docutils literal notranslate"><span class="pre">try:</span> <span class="pre">...</span> <span class="pre">except</span> <span class="pre">BaseExceptionGroup:</span> <span class="pre">...</span></code>.</p>
<p>Both have a constructor that takes two positional-only arguments: a message
string and a sequence of the nested exceptions, which are exposed in the
fields <code class="docutils literal notranslate"><span class="pre">message</span></code> and <code class="docutils literal notranslate"><span class="pre">exceptions</span></code>. For example:
<code class="docutils literal notranslate"><span class="pre">ExceptionGroup('issues',</span> <span class="pre">[ValueError('bad</span> <span class="pre">value'),</span> <span class="pre">TypeError('bad</span> <span class="pre">type')])</span></code>.
The difference between them is that <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> can only wrap
<code class="docutils literal notranslate"><span class="pre">Exception</span></code> subclasses while <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> can wrap any
<code class="docutils literal notranslate"><span class="pre">BaseException</span></code> subclass. The <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> constructor
inspects the nested exceptions and if they are all <code class="docutils literal notranslate"><span class="pre">Exception</span></code> subclasses,
it returns an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> rather than a <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>. The
<code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> constructor raises a <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> if any of the nested
exceptions is not an <code class="docutils literal notranslate"><span class="pre">Exception</span></code> instance.  In the rest of the document,
when we refer to an exception group, we mean either an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
or a <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>. When it is necessary to make the distinction,
we use the class name. For brevity, we will use <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> in code
examples that are relevant to both.</p>
<p>Since an exception group can be nested, it represents a tree of exceptions,
where the leaves are plain exceptions and each internal node represents a time
at which the program grouped some unrelated exceptions into a new group and
raised them together.</p>
<p>The <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup.subgroup(condition)</span></code> method gives us a way to obtain
an exception group that has the same metadata (message, cause, context,
traceback) as the original group, and the same nested structure of groups, but
contains only those exceptions for which the condition is true:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span> <span class="o">=</span> <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>    <span class="s2">&quot;one&quot;</span><span class="p">,</span>
<span class="gp">... </span>    <span class="p">[</span>
<span class="gp">... </span>        <span class="ne">TypeError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span>
<span class="gp">... </span>        <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>            <span class="s2">&quot;two&quot;</span><span class="p">,</span>
<span class="gp">... </span>             <span class="p">[</span><span class="ne">TypeError</span><span class="p">(</span><span class="mi">2</span><span class="p">),</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">3</span><span class="p">)]</span>
<span class="gp">... </span>        <span class="p">),</span>
<span class="gp">... </span>        <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>             <span class="s2">&quot;three&quot;</span><span class="p">,</span>
<span class="gp">... </span>              <span class="p">[</span><span class="ne">OSError</span><span class="p">(</span><span class="mi">4</span><span class="p">)]</span>
<span class="gp">... </span>        <span class="p">)</span>
<span class="gp">... </span>    <span class="p">]</span>
<span class="gp">... </span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span><span class="w"> </span><span class="nn">traceback</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="n">eg</span><span class="p">)</span>
<span class="go">  | ExceptionGroup: one (3 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | TypeError: 1</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | ExceptionGroup: two (2 sub-exceptions)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: 2</span>
<span class="go">      +---------------- 2 ----------------</span>
<span class="go">      | ValueError: 3</span>
<span class="go">      +------------------------------------</span>
<span class="go">    +---------------- 3 ----------------</span>
<span class="go">    | ExceptionGroup: three (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | OSError: 4</span>
<span class="go">      +------------------------------------</span>

<span class="gp">&gt;&gt;&gt; </span><span class="n">type_errors</span> <span class="o">=</span> <span class="n">eg</span><span class="o">.</span><span class="n">subgroup</span><span class="p">(</span><span class="k">lambda</span> <span class="n">e</span><span class="p">:</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">e</span><span class="p">,</span> <span class="ne">TypeError</span><span class="p">))</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="n">type_errors</span><span class="p">)</span>
<span class="go">  | ExceptionGroup: one (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | TypeError: 1</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | ExceptionGroup: two (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: 2</span>
<span class="go">      +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>The match condition is also applied to interior nodes (the exception
groups), and a match causes the whole subtree rooted at this node
to be included in the result.</p>
<p>Empty nested groups are omitted from the result, as in the
case of <code class="docutils literal notranslate"><span class="pre">ExceptionGroup(&quot;three&quot;)</span></code> in the example above.  If none of the
exceptions match the condition, <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> returns <code class="docutils literal notranslate"><span class="pre">None</span></code> rather
than an empty group. The original <code class="docutils literal notranslate"><span class="pre">eg</span></code>
is unchanged by <code class="docutils literal notranslate"><span class="pre">subgroup</span></code>, but the value returned is not necessarily a full
new copy. Leaf exceptions are not copied, nor are exception groups which are
fully contained in the result. When it is necessary to partition a
group because the condition holds for some, but not all of its
contained exceptions, a new <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> or <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>
instance is created, while the <code class="docutils literal notranslate"><span class="pre">__cause__</span></code>, <code class="docutils literal notranslate"><span class="pre">__context__</span></code> and
<code class="docutils literal notranslate"><span class="pre">__traceback__</span></code> fields are copied by reference, so they are shared with
the original <code class="docutils literal notranslate"><span class="pre">eg</span></code>.</p>
<p>If both the subgroup and its complement are needed, the
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup.split(condition)</span></code> method can be used:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">type_errors</span><span class="p">,</span> <span class="n">other_errors</span> <span class="o">=</span> <span class="n">eg</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="k">lambda</span> <span class="n">e</span><span class="p">:</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">e</span><span class="p">,</span> <span class="ne">TypeError</span><span class="p">))</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="n">type_errors</span><span class="p">)</span>
<span class="go">  | ExceptionGroup: one (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | TypeError: 1</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | ExceptionGroup: two (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: 2</span>
<span class="go">      +------------------------------------</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="n">other_errors</span><span class="p">)</span>
<span class="go">  | ExceptionGroup: one (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | ExceptionGroup: two (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | ValueError: 3</span>
<span class="go">      +------------------------------------</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | ExceptionGroup: three (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | OSError: 4</span>
<span class="go">      +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>If a split is trivial (one side is empty), then None is returned for the
other side:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">other_errors</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="k">lambda</span> <span class="n">e</span><span class="p">:</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">e</span><span class="p">,</span> <span class="ne">SyntaxError</span><span class="p">))</span>
<span class="go">(None, ExceptionGroup(&#39;one&#39;, [</span>
<span class="go">  ExceptionGroup(&#39;two&#39;, [</span>
<span class="go">    ValueError(3)</span>
<span class="go">  ]),</span>
<span class="go">  ExceptionGroup(&#39;three&#39;, [</span>
<span class="go">    OSError(4)])]))</span>
</pre></div>
</div>
<p>Since splitting by exception type is a very common use case, <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> and
<code class="docutils literal notranslate"><span class="pre">split</span></code> can take an exception type or tuple of exception types and treat it
as a shorthand for matching that type: <code class="docutils literal notranslate"><span class="pre">eg.split(T)</span></code> divides <code class="docutils literal notranslate"><span class="pre">eg</span></code> into the
subgroup of leaf exceptions that match the type <code class="docutils literal notranslate"><span class="pre">T</span></code>, and the subgroup of those
that do not (using the same check as <code class="docutils literal notranslate"><span class="pre">except</span></code> for a match).</p>
<section id="subclassing-exception-groups">
<h4><a class="toc-backref" href="#subclassing-exception-groups" role="doc-backlink">Subclassing Exception Groups</a></h4>
<p>It is possible to subclass exception groups, but when doing that it is
usually necessary to specify how <code class="docutils literal notranslate"><span class="pre">subgroup()</span></code> and <code class="docutils literal notranslate"><span class="pre">split()</span></code> should
create new instances for the matching or non-matching part of the partition.
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> exposes an instance method <code class="docutils literal notranslate"><span class="pre">derive(self,</span> <span class="pre">excs)</span></code>
which is called whenever <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> and <code class="docutils literal notranslate"><span class="pre">split</span></code> need to create a new
exception group. The parameter <code class="docutils literal notranslate"><span class="pre">excs</span></code> is the sequence of exceptions to
include in the new group. Since <code class="docutils literal notranslate"><span class="pre">derive</span></code> has access to self, it can
copy data from it to the new object. For example, if we need an exception
group subclass that has an additional error code field, we can do this:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">class</span><span class="w"> </span><span class="nc">MyExceptionGroup</span><span class="p">(</span><span class="n">ExceptionGroup</span><span class="p">):</span>
    <span class="k">def</span><span class="w"> </span><span class="fm">__new__</span><span class="p">(</span><span class="bp">cls</span><span class="p">,</span> <span class="n">message</span><span class="p">,</span> <span class="n">excs</span><span class="p">,</span> <span class="n">errcode</span><span class="p">):</span>
        <span class="n">obj</span> <span class="o">=</span> <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__new__</span><span class="p">(</span><span class="bp">cls</span><span class="p">,</span> <span class="n">message</span><span class="p">,</span> <span class="n">excs</span><span class="p">)</span>
        <span class="n">obj</span><span class="o">.</span><span class="n">errcode</span> <span class="o">=</span> <span class="n">errcode</span>
        <span class="k">return</span> <span class="n">obj</span>

    <span class="k">def</span><span class="w"> </span><span class="nf">derive</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">excs</span><span class="p">):</span>
        <span class="k">return</span> <span class="n">MyExceptionGroup</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">message</span><span class="p">,</span> <span class="n">excs</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">errcode</span><span class="p">)</span>
</pre></div>
</div>
<p>Note that we override <code class="docutils literal notranslate"><span class="pre">__new__</span></code> rather than <code class="docutils literal notranslate"><span class="pre">__init__</span></code>; this is because
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup.__new__</span></code> needs to inspect the constructor arguments, and
its signature is different from that of the subclass. Note also that our
<code class="docutils literal notranslate"><span class="pre">derive</span></code> function does not copy the <code class="docutils literal notranslate"><span class="pre">__context__</span></code>, <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> and
<code class="docutils literal notranslate"><span class="pre">__traceback__</span></code> fields, because <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> and <code class="docutils literal notranslate"><span class="pre">split</span></code> do that for us.</p>
<p>With the class defined above, we have the following:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span> <span class="o">=</span> <span class="n">MyExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">TypeError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">2</span><span class="p">)],</span> <span class="mi">42</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">match</span><span class="p">,</span> <span class="n">rest</span> <span class="o">=</span> <span class="n">eg</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;match: </span><span class="si">{</span><span class="n">match</span><span class="si">!r}</span><span class="s1">: </span><span class="si">{</span><span class="n">match</span><span class="o">.</span><span class="n">errcode</span><span class="si">}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="go">match: MyExceptionGroup(&#39;eg&#39;, [ValueError(2)], 42): 42</span>
<span class="gp">&gt;&gt;&gt; </span><span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;rest: </span><span class="si">{</span><span class="n">rest</span><span class="si">!r}</span><span class="s1">: </span><span class="si">{</span><span class="n">rest</span><span class="o">.</span><span class="n">errcode</span><span class="si">}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="go">rest: MyExceptionGroup(&#39;eg&#39;, [TypeError(1)], 42): 42</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>If we do not override <code class="docutils literal notranslate"><span class="pre">derive</span></code>, then split calls the one defined
on <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>, which returns an instance of <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
if all contained exceptions are of type <code class="docutils literal notranslate"><span class="pre">Exception</span></code>, and
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> otherwise. For example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span><span class="w"> </span><span class="nc">MyExceptionGroup</span><span class="p">(</span><span class="n">BaseExceptionGroup</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">pass</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span> <span class="o">=</span> <span class="n">MyExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">ValueError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="ne">KeyboardInterrupt</span><span class="p">(</span><span class="mi">2</span><span class="p">)])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">match</span><span class="p">,</span> <span class="n">rest</span> <span class="o">=</span> <span class="n">eg</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;match: </span><span class="si">{</span><span class="n">match</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="go">match: ExceptionGroup(&#39;eg&#39;, [ValueError(1)])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;rest: </span><span class="si">{</span><span class="n">rest</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="go">rest: BaseExceptionGroup(&#39;eg&#39;, [KeyboardInterrupt(2)])</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="the-traceback-of-an-exception-group">
<h4><a class="toc-backref" href="#the-traceback-of-an-exception-group" role="doc-backlink">The Traceback of an Exception Group</a></h4>
<p>For regular exceptions, the traceback represents a simple path of frames,
from the frame in which the exception was raised to the frame in which it
was caught or, if it hasn’t been caught yet, the frame that the program’s
execution is currently in. The list is constructed by the interpreter, which
appends any frame from which it exits to the traceback of the ‘current
exception’ if one exists. To support efficient appends, the links in a
traceback’s list of frames are from the oldest to the newest frame. Appending
a new frame is then simply a matter of inserting a new head to the linked
list referenced from the exception’s <code class="docutils literal notranslate"><span class="pre">__traceback__</span></code> field. Crucially, the
traceback’s frame list is immutable in the sense that frames only need to be
added at the head, and never need to be removed.</p>
<p>We do not need to make any changes to this data structure. The <code class="docutils literal notranslate"><span class="pre">__traceback__</span></code>
field of the exception group instance represents the path that the contained
exceptions travelled through together after being joined into the
group, and the same field on each of the nested exceptions
represents the path through which this exception arrived at the frame of the
merge.</p>
<p>What we do need to change is any code that interprets and displays tracebacks,
because it now needs to continue into tracebacks of nested exceptions, as
in the following example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span><span class="w"> </span><span class="nf">f</span><span class="p">(</span><span class="n">v</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="n">v</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">return</span> <span class="n">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;one&quot;</span><span class="p">,</span> <span class="p">[</span><span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)])</span>
<span class="gp">... </span><span class="k">except</span> <span class="n">ExceptionGroup</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="n">eg</span> <span class="o">=</span> <span class="n">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;two&quot;</span><span class="p">,</span> <span class="p">[</span><span class="n">f</span><span class="p">(</span><span class="mi">2</span><span class="p">),</span> <span class="n">eg</span><span class="p">])</span>
<span class="go"> + Exception Group Traceback (most recent call last):</span>
<span class="go"> |   File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;</span>
<span class="go"> | ExceptionGroup: two (2 sub-exceptions)</span>
<span class="go"> +-+---------------- 1 ----------------</span>
<span class="go">   | Traceback (most recent call last):</span>
<span class="go">   |   File &quot;&lt;stdin&gt;&quot;, line 3, in f</span>
<span class="go">   | ValueError: 2</span>
<span class="go">   +---------------- 2 ----------------</span>
<span class="go">   | Exception Group Traceback (most recent call last):</span>
<span class="go">   |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">   | ExceptionGroup: one (1 sub-exception)</span>
<span class="go">   +-+---------------- 1 ----------------</span>
<span class="go">     | Traceback (most recent call last):</span>
<span class="go">     |   File &quot;&lt;stdin&gt;&quot;, line 3, in f</span>
<span class="go">     | ValueError: 1</span>
<span class="go">     +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="handling-exception-groups">
<h4><a class="toc-backref" href="#handling-exception-groups" role="doc-backlink">Handling Exception Groups</a></h4>
<p>We expect that when programs catch and handle exception groups, they will
typically either query to check if it has leaf exceptions for which some
condition holds (using <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> or <code class="docutils literal notranslate"><span class="pre">split</span></code>) or format the exception
(using the <code class="docutils literal notranslate"><span class="pre">traceback</span></code> module’s methods).</p>
<p>It is less likely to be useful to iterate over the individual leaf exceptions.
To see why, suppose that an application caught an exception group raised by
an <code class="docutils literal notranslate"><span class="pre">asyncio.gather()</span></code> call. At this stage, the context for each specific
exception is lost. Any recovery for this exception should have been performed
before it was grouped with other exceptions <a class="footnote-reference brackets" href="#id28" id="id13">[10]</a>.
Furthermore, the application is likely to react in the same way to any number
of instances of a certain exception type, so it is more likely that we will
want to know whether <code class="docutils literal notranslate"><span class="pre">eg.subgroup(T)</span></code> is None or not, than we are to be
interested in the number of <code class="docutils literal notranslate"><span class="pre">Ts</span></code> in <code class="docutils literal notranslate"><span class="pre">eg</span></code>.</p>
<p>However, there are situations where it is necessary to inspect the
individual leaf exceptions. For example, suppose that we have an
exception group <code class="docutils literal notranslate"><span class="pre">eg</span></code> and that we want to log the <code class="docutils literal notranslate"><span class="pre">OSErrors</span></code> that have a
specific error code and reraise everything else. We can do this by passing
a function with side effects to <code class="docutils literal notranslate"><span class="pre">subgroup</span></code>, as follows:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span><span class="w"> </span><span class="nf">log_and_ignore_ENOENT</span><span class="p">(</span><span class="n">err</span><span class="p">):</span>
    <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">err</span><span class="p">,</span> <span class="ne">OSError</span><span class="p">)</span> <span class="ow">and</span> <span class="n">err</span><span class="o">.</span><span class="n">errno</span> <span class="o">==</span> <span class="n">ENOENT</span><span class="p">:</span>
        <span class="n">log</span><span class="p">(</span><span class="n">err</span><span class="p">)</span>
        <span class="k">return</span> <span class="kc">False</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">return</span> <span class="kc">True</span>

<span class="k">try</span><span class="p">:</span>
    <span class="o">.</span> <span class="o">.</span> <span class="o">.</span>
<span class="k">except</span> <span class="n">ExceptionGroup</span> <span class="k">as</span> <span class="n">eg</span><span class="p">:</span>
    <span class="n">eg</span> <span class="o">=</span> <span class="n">eg</span><span class="o">.</span><span class="n">subgroup</span><span class="p">(</span><span class="n">log_and_ignore_ENOENT</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">eg</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span>
        <span class="k">raise</span> <span class="n">eg</span>
</pre></div>
</div>
<p>In the previous example, when <code class="docutils literal notranslate"><span class="pre">log_and_ignore_ENOENT</span></code> is invoked on a leaf
exception, only part of this exception’s traceback is accessible – the part
referenced from its <code class="docutils literal notranslate"><span class="pre">__traceback__</span></code> field. If we need the full traceback,
we need to look at the concatenation of the tracebacks of the exceptions on
the path from the root to this leaf. We can get that with direct iteration,
recursively, as follows:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span><span class="w"> </span><span class="nf">leaf_generator</span><span class="p">(</span><span class="n">exc</span><span class="p">,</span> <span class="n">tbs</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">tbs</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
        <span class="n">tbs</span> <span class="o">=</span> <span class="p">[]</span>

    <span class="n">tbs</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">exc</span><span class="o">.</span><span class="n">__traceback__</span><span class="p">)</span>
    <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">exc</span><span class="p">,</span> <span class="n">BaseExceptionGroup</span><span class="p">):</span>
        <span class="k">for</span> <span class="n">e</span> <span class="ow">in</span> <span class="n">exc</span><span class="o">.</span><span class="n">exceptions</span><span class="p">:</span>
            <span class="k">yield from</span> <span class="n">leaf_generator</span><span class="p">(</span><span class="n">e</span><span class="p">,</span> <span class="n">tbs</span><span class="p">)</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="c1"># exc is a leaf exception and its traceback</span>
        <span class="c1"># is the concatenation of the traceback</span>
        <span class="c1"># segments in tbs.</span>

        <span class="c1"># Note: the list returned (tbs) is reused in each iteration</span>
        <span class="c1"># through the generator. Make a copy if your use case holds</span>
        <span class="c1"># on to it beyond the current iteration or mutates its contents.</span>

        <span class="k">yield</span> <span class="n">exc</span><span class="p">,</span> <span class="n">tbs</span>
    <span class="n">tbs</span><span class="o">.</span><span class="n">pop</span><span class="p">()</span>
</pre></div>
</div>
<p>We can then process the full tracebacks of the leaf exceptions:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span><span class="w"> </span><span class="nn">traceback</span>
<span class="gp">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">def</span><span class="w"> </span><span class="nf">g</span><span class="p">(</span><span class="n">v</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="n">v</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">return</span> <span class="n">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">def</span><span class="w"> </span><span class="nf">f</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="n">g</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="n">g</span><span class="p">(</span><span class="mi">2</span><span class="p">)])</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="n">f</span><span class="p">()</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">BaseException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="n">eg</span> <span class="o">=</span> <span class="n">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">for</span> <span class="p">(</span><span class="n">i</span><span class="p">,</span> <span class="p">(</span><span class="n">exc</span><span class="p">,</span> <span class="n">tbs</span><span class="p">))</span> <span class="ow">in</span> <span class="nb">enumerate</span><span class="p">(</span><span class="n">leaf_generator</span><span class="p">(</span><span class="n">eg</span><span class="p">)):</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;</span><span class="se">\n</span><span class="s2">=== Exception #</span><span class="si">{</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="si">}</span><span class="s2">:&quot;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="n">exc</span><span class="p">)</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;The complete traceback for Exception #</span><span class="si">{</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="si">}</span><span class="s2">:&quot;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">for</span> <span class="n">tb</span> <span class="ow">in</span> <span class="n">tbs</span><span class="p">:</span>
<span class="gp">... </span>        <span class="n">traceback</span><span class="o">.</span><span class="n">print_tb</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
<span class="gp">...</span>

<span class="go">=== Exception #1:</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">g</span>
<span class="gr">ValueError</span>: <span class="n">1</span>
<span class="x">The complete traceback for Exception #1</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">f</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">g</span>

<span class="x">=== Exception #2:</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">g</span>
<span class="gr">ValueError</span>: <span class="n">2</span>
<span class="x">The complete traceback for Exception #2:</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">f</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">g</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
</section>
<section id="except">
<h3><a class="toc-backref" href="#except" role="doc-backlink">except*</a></h3>
<p>We are proposing to introduce a new variant of the <code class="docutils literal notranslate"><span class="pre">try..except</span></code> syntax to
simplify working with exception groups. The <code class="docutils literal notranslate"><span class="pre">*</span></code> symbol indicates that multiple
exceptions can be handled by each <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span> <span class="n">SpamError</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span> <span class="n">FooError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span> <span class="p">(</span><span class="n">BarError</span><span class="p">,</span> <span class="n">BazError</span><span class="p">)</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="o">...</span>
</pre></div>
</div>
<p>In a traditional <code class="docutils literal notranslate"><span class="pre">try-except</span></code> statement there is only one exception to handle,
so the body of at most one <code class="docutils literal notranslate"><span class="pre">except</span></code> clause executes; the first one that matches
the exception. With the new syntax, an <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause can match a subgroup
of the exception group that was raised, while the remaining part is matched
by following <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses. In other words, a single exception group can
cause several <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses to execute, but each such clause executes at
most once (for all matching exceptions from the group) and each exception is
either handled by exactly one clause (the first one that matches its type)
or is reraised at the end. The manner in which each exception is handled by
a <code class="docutils literal notranslate"><span class="pre">try-except*</span></code> block is independent of any other exceptions in the group.</p>
<p>For example, suppose that the body of the <code class="docutils literal notranslate"><span class="pre">try</span></code> block above raises
<code class="docutils literal notranslate"><span class="pre">eg</span> <span class="pre">=</span> <span class="pre">ExceptionGroup('msg',</span> <span class="pre">[FooError(1),</span> <span class="pre">FooError(2),</span> <span class="pre">BazError()])</span></code>.
The <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses are evaluated in order by calling <code class="docutils literal notranslate"><span class="pre">split</span></code> on the
<code class="docutils literal notranslate"><span class="pre">unhandled</span></code> exception group, which is initially equal to <code class="docutils literal notranslate"><span class="pre">eg</span></code> and then shrinks
as exceptions are matched and extracted from it.  In the first <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause,
<code class="docutils literal notranslate"><span class="pre">unhandled.split(SpamError)</span></code> returns <code class="docutils literal notranslate"><span class="pre">(None,</span> <span class="pre">unhandled)</span></code> so the body of this
block is not executed and <code class="docutils literal notranslate"><span class="pre">unhandled</span></code> is unchanged. For the second block,
<code class="docutils literal notranslate"><span class="pre">unhandled.split(FooError)</span></code> returns a non-trivial split <code class="docutils literal notranslate"><span class="pre">(match,</span> <span class="pre">rest)</span></code> with
<code class="docutils literal notranslate"><span class="pre">match</span> <span class="pre">=</span> <span class="pre">ExceptionGroup('msg',</span> <span class="pre">[FooError(1),</span> <span class="pre">FooError(2)])</span></code>
and <code class="docutils literal notranslate"><span class="pre">rest</span> <span class="pre">=</span> <span class="pre">ExceptionGroup('msg',</span> <span class="pre">[BazError()])</span></code>. The body of this <code class="docutils literal notranslate"><span class="pre">except*</span></code>
block is executed, with the value of <code class="docutils literal notranslate"><span class="pre">e</span></code> and <code class="docutils literal notranslate"><span class="pre">sys.exc_info()</span></code> set to <code class="docutils literal notranslate"><span class="pre">match</span></code>.
Then, <code class="docutils literal notranslate"><span class="pre">unhandled</span></code> is set to <code class="docutils literal notranslate"><span class="pre">rest</span></code>.
Finally, the third block matches the remaining exception so it is executed
with <code class="docutils literal notranslate"><span class="pre">e</span></code> and <code class="docutils literal notranslate"><span class="pre">sys.exc_info()</span></code> set to <code class="docutils literal notranslate"><span class="pre">ExceptionGroup('msg',</span> <span class="pre">[BazError()])</span></code>.</p>
<p>Exceptions are matched using a subclass check. For example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">low_level_os_operation</span><span class="p">()</span>
<span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">eg</span><span class="p">:</span>
    <span class="k">for</span> <span class="n">e</span> <span class="ow">in</span> <span class="n">eg</span><span class="o">.</span><span class="n">exceptions</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="o">.</span><span class="vm">__name__</span><span class="p">)</span>
</pre></div>
</div>
<p>could output:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="ne">BlockingIOError</span>
<span class="ne">ConnectionRefusedError</span>
<span class="ne">OSError</span>
<span class="ne">InterruptedError</span>
<span class="ne">BlockingIOError</span>
</pre></div>
</div>
<p>The order of <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses is significant just like with the regular
<code class="docutils literal notranslate"><span class="pre">try..except</span></code>:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;problem&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">BlockingIOError</span><span class="p">()])</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>   <span class="c1"># Would catch the error</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">BlockingIOError</span><span class="p">:</span> <span class="c1"># Would never run</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;never&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">ExceptionGroup(&#39;problem&#39;, [BlockingIOError()])</span>
</pre></div>
</div>
<section id="recursive-matching">
<h4><a class="toc-backref" href="#recursive-matching" role="doc-backlink">Recursive Matching</a></h4>
<p>The matching of <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses against an exception group is performed
recursively, using the <code class="docutils literal notranslate"><span class="pre">split()</span></code> method:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>        <span class="s2">&quot;eg&quot;</span><span class="p">,</span>
<span class="gp">... </span>        <span class="p">[</span>
<span class="gp">... </span>            <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;a&#39;</span><span class="p">),</span>
<span class="gp">... </span>            <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;b&#39;</span><span class="p">),</span>
<span class="gp">... </span>            <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>                <span class="s2">&quot;nested&quot;</span><span class="p">,</span>
<span class="gp">... </span>                <span class="p">[</span><span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;c&#39;</span><span class="p">),</span> <span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;d&#39;</span><span class="p">)])</span>
<span class="gp">... </span>        <span class="p">]</span>
<span class="gp">... </span>    <span class="p">)</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">e1</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;e1 = </span><span class="si">{</span><span class="n">e1</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e2</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;e2 = </span><span class="si">{</span><span class="n">e2</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">e1 = ExceptionGroup(&#39;eg&#39;, [TypeError(&#39;b&#39;), ExceptionGroup(&#39;nested&#39;, [TypeError(&#39;c&#39;)])])</span>
<span class="go">e2 = ExceptionGroup(&#39;eg&#39;, [ValueError(&#39;a&#39;), ExceptionGroup(&#39;nested&#39;, [KeyError(&#39;d&#39;)])])</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="unmatched-exceptions">
<h4><a class="toc-backref" href="#unmatched-exceptions" role="doc-backlink">Unmatched Exceptions</a></h4>
<p>If not all exceptions in an exception group were matched by the <code class="docutils literal notranslate"><span class="pre">except*</span></code>
clauses, the remaining part of the group is propagated on:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>            <span class="s2">&quot;msg&quot;</span><span class="p">,</span> <span class="p">[</span>
<span class="gp">... </span>                 <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;a&#39;</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;b&#39;</span><span class="p">),</span>
<span class="gp">... </span>                 <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;c&#39;</span><span class="p">),</span> <span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;e&#39;</span><span class="p">)</span>
<span class="gp">... </span>            <span class="p">]</span>
<span class="gp">... </span>        <span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;got some ValueErrors: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;got some TypeErrors: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="n">ExceptionGroup</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;propagated: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">got some ValueErrors: ExceptionGroup(&#39;msg&#39;, [ValueError(&#39;a&#39;)])</span>
<span class="go">got some TypeErrors: ExceptionGroup(&#39;msg&#39;, [TypeError(&#39;b&#39;), TypeError(&#39;c&#39;)])</span>
<span class="go">propagated: ExceptionGroup(&#39;msg&#39;, [KeyError(&#39;e&#39;)])</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="naked-exceptions">
<h4><a class="toc-backref" href="#naked-exceptions" role="doc-backlink">Naked Exceptions</a></h4>
<p>If the exception raised inside the <code class="docutils literal notranslate"><span class="pre">try</span></code> body is not of type <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
or <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>, we call it a <code class="docutils literal notranslate"><span class="pre">naked</span></code> exception. If its type matches
one of the <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses, it is caught and wrapped by an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
(or <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> if it is not an <code class="docutils literal notranslate"><span class="pre">Exception</span></code> subclass) with an empty
message string. This is to make the type of <code class="docutils literal notranslate"><span class="pre">e</span></code> consistent and statically known:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">BlockingIOError</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">...</span>
<span class="go">ExceptionGroup(&#39;&#39;, [BlockingIOError()])</span>
</pre></div>
</div>
<p>However, if a naked exception is not caught, it propagates in its original
naked form:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">12</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;never&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;caught ValueError: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">caught ValueError: ValueError(12)</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="raising-exceptions-in-an-except-block">
<h4><a class="toc-backref" href="#raising-exceptions-in-an-except-block" role="doc-backlink">Raising exceptions in an <code class="docutils literal notranslate"><span class="pre">except*</span></code> block</a></h4>
<p>In a traditional <code class="docutils literal notranslate"><span class="pre">except</span></code> block, there are two ways to raise exceptions:
<code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">e</span></code> to explicitly raise an exception object <code class="docutils literal notranslate"><span class="pre">e</span></code>, or naked <code class="docutils literal notranslate"><span class="pre">raise</span></code> to
reraise the ‘current exception’. When <code class="docutils literal notranslate"><span class="pre">e</span></code> is the current exception, the two
forms are not equivalent because a reraise does not add the current frame to
the stack:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span><span class="w"> </span><span class="nf">foo</span><span class="p">():</span>                           <span class="o">|</span> <span class="k">def</span><span class="w"> </span><span class="nf">foo</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>                             <span class="o">|</span>     <span class="k">try</span><span class="p">:</span>
        <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>                        <span class="o">|</span>         <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
    <span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>   <span class="o">|</span>     <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
        <span class="k">raise</span> <span class="n">e</span>                      <span class="o">|</span>         <span class="k">raise</span>
                                     <span class="o">|</span>
<span class="n">foo</span><span class="p">()</span>                                <span class="o">|</span> <span class="n">foo</span><span class="p">()</span>
                                     <span class="o">|</span>
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>   <span class="o">|</span> <span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&quot;/Users/guido/a.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">7</span>   <span class="o">|</span>   <span class="n">File</span> <span class="s2">&quot;/Users/guido/b.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">7</span>
   <span class="n">foo</span><span class="p">()</span>                             <span class="o">|</span>     <span class="n">foo</span><span class="p">()</span>
  <span class="n">File</span> <span class="s2">&quot;/Users/guido/a.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">5</span>   <span class="o">|</span>   <span class="n">File</span> <span class="s2">&quot;/Users/guido/b.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span>
   <span class="k">raise</span> <span class="n">e</span>                           <span class="o">|</span>     <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
  <span class="n">File</span> <span class="s2">&quot;/Users/guido/a.py&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span>   <span class="o">|</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>
   <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>                               <span class="o">|</span>
<span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>  <span class="o">|</span>
</pre></div>
</div>
<p>This holds for exception groups as well, but the situation is now more complex
because there can be exceptions raised and reraised from multiple <code class="docutils literal notranslate"><span class="pre">except*</span></code>
clauses, as well as unhandled exceptions that need to propagate.
The interpreter needs to combine all those exceptions into a result, and
raise that.</p>
<p>The reraised exceptions and the unhandled exceptions are subgroups of the
original group, and share its metadata (cause, context, traceback).
On the other hand, each of the explicitly raised exceptions has its own
metadata - the traceback contains the line from which it was raised, its
cause is whatever it may have been explicitly chained to, and its context is the
value of <code class="docutils literal notranslate"><span class="pre">sys.exc_info()</span></code> in the <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause of the raise.</p>
<p>In the aggregated exception group, the reraised and unhandled exceptions have
the same relative structure as in the original exception, as if they were split
off together in one <code class="docutils literal notranslate"><span class="pre">subgroup</span></code> call. For example, in the snippet below the
inner <code class="docutils literal notranslate"><span class="pre">try-except*</span></code> block raises an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> that contains all
<code class="docutils literal notranslate"><span class="pre">ValueErrors</span></code> and <code class="docutils literal notranslate"><span class="pre">TypeErrors</span></code> merged back into the same shape they had in
the original <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>        <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>            <span class="s2">&quot;eg&quot;</span><span class="p">,</span>
<span class="gp">... </span>            <span class="p">[</span>
<span class="gp">... </span>                <span class="ne">ValueError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span>
<span class="gp">... </span>                <span class="ne">TypeError</span><span class="p">(</span><span class="mi">2</span><span class="p">),</span>
<span class="gp">... </span>                <span class="ne">OSError</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">... </span>                <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>                    <span class="s2">&quot;nested&quot;</span><span class="p">,</span>
<span class="gp">... </span>                    <span class="p">[</span><span class="ne">OSError</span><span class="p">(</span><span class="mi">4</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">6</span><span class="p">)])</span>
<span class="gp">... </span>            <span class="p">]</span>
<span class="gp">... </span>        <span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;*ValueError: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span>        <span class="k">raise</span>
<span class="gp">... </span>    <span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;*OSError: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="n">ExceptionGroup</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">...</span>
<span class="go">*ValueError: ExceptionGroup(&#39;eg&#39;, [ValueError(1), ExceptionGroup(&#39;nested&#39;, [ValueError(6)])])</span>
<span class="go">*OSError: ExceptionGroup(&#39;eg&#39;, [OSError(3), ExceptionGroup(&#39;nested&#39;, [OSError(4)])])</span>
<span class="go">ExceptionGroup(&#39;eg&#39;, [ValueError(1), TypeError(2), ExceptionGroup(&#39;nested&#39;, [TypeError(5), ValueError(6)])])</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>When exceptions are raised explicitly, they are independent of the original
exception group, and cannot be merged with it (they have their own cause,
context and traceback). Instead, they are combined into a new <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>
(or <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>), which also contains the reraised/unhandled
subgroup described above.</p>
<p>In the following example, the <code class="docutils literal notranslate"><span class="pre">ValueErrors</span></code> were raised so they are in their
own <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>, while the <code class="docutils literal notranslate"><span class="pre">OSErrors</span></code> were reraised so they were
merged with the unhandled <code class="docutils literal notranslate"><span class="pre">TypeErrors</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>        <span class="s2">&quot;eg&quot;</span><span class="p">,</span>
<span class="gp">... </span>        <span class="p">[</span>
<span class="gp">... </span>            <span class="ne">ValueError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span>
<span class="gp">... </span>            <span class="ne">TypeError</span><span class="p">(</span><span class="mi">2</span><span class="p">),</span>
<span class="gp">... </span>            <span class="ne">OSError</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span>
<span class="gp">... </span>            <span class="n">ExceptionGroup</span><span class="p">(</span>
<span class="gp">... </span>                <span class="s2">&quot;nested&quot;</span><span class="p">,</span>
<span class="gp">... </span>                <span class="p">[</span><span class="ne">OSError</span><span class="p">(</span><span class="mi">4</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="mi">5</span><span class="p">),</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">6</span><span class="p">)])</span>
<span class="gp">... </span>        <span class="p">]</span>
<span class="gp">... </span>    <span class="p">)</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;*ValueError: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">e</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;*OSError: </span><span class="si">{</span><span class="n">e</span><span class="si">!r}</span><span class="s1">&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">raise</span>
<span class="gp">...</span>
<span class="go">*ValueError: ExceptionGroup(&#39;eg&#39;, [ValueError(1), ExceptionGroup(&#39;nested&#39;, [ValueError(6)])])</span>
<span class="go">*OSError: ExceptionGroup(&#39;eg&#39;, [OSError(3), ExceptionGroup(&#39;nested&#39;, [OSError(4)])])</span>
<span class="go">  | ExceptionGroup:  (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 15, in &lt;module&gt;</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: eg (2 sub-exceptions)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | ValueError: 1</span>
<span class="go">      +---------------- 2 ----------------</span>
<span class="go">      | ExceptionGroup: nested (1 sub-exception)</span>
<span class="go">      +-+---------------- 1 ----------------</span>
<span class="go">        | ValueError: 6</span>
<span class="go">        +------------------------------------</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: eg (3 sub-exceptions)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: 2</span>
<span class="go">      +---------------- 2 ----------------</span>
<span class="go">      | OSError: 3</span>
<span class="go">      +---------------- 3 ----------------</span>
<span class="go">      | ExceptionGroup: nested (2 sub-exceptions)</span>
<span class="go">      +-+---------------- 1 ----------------</span>
<span class="go">        | OSError: 4</span>
<span class="go">        +---------------- 2 ----------------</span>
<span class="go">        | TypeError: 5</span>
<span class="go">        +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="chaining">
<h4><a class="toc-backref" href="#chaining" role="doc-backlink">Chaining</a></h4>
<p>Explicitly raised exception groups are chained as with any exceptions. The
following example shows how part of <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> “one” became the
context for <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> “two”, while the other part was combined with
it into the new <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;one&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;a&#39;</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;b&#39;</span><span class="p">)])</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;two&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;x&#39;</span><span class="p">),</span> <span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;y&#39;</span><span class="p">)])</span>
<span class="gp">...</span>
<span class="go">  | ExceptionGroup:  (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: one (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | ValueError: a</span>
<span class="go">      +------------------------------------</span>
<span class="go">    |</span>
<span class="go">    | During handling of the above exception, another exception occurred:</span>
<span class="go">    |</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 4, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: two (2 sub-exceptions)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | KeyError: &#39;x&#39;</span>
<span class="go">      +---------------- 2 ----------------</span>
<span class="go">      | KeyError: &#39;y&#39;</span>
<span class="go">      +------------------------------------</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: one (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: b</span>
<span class="go">      +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="raising-new-exceptions">
<h4><a class="toc-backref" href="#raising-new-exceptions" role="doc-backlink">Raising New Exceptions</a></h4>
<p>In the previous examples the explicit raises were of the exceptions that
were caught, so for completion we show a new exception being raised, with
chaining:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;bad type&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;bad value&#39;</span><span class="p">)</span> <span class="kn">from</span><span class="w"> </span><span class="nn">e</span>
<span class="gp">...</span>
<span class="go">  | ExceptionGroup:  (1 sub-exception)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | TypeError: bad type</span>
<span class="go">    +------------------------------------</span>

<span class="go">The above exception was the direct cause of the following exception:</span>

<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">4</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">ValueError</span>: <span class="n">bad value</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>Note that exceptions raised in one <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause are not eligible to match
other clauses from the same <code class="docutils literal notranslate"><span class="pre">try</span></code> statement:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="mi">2</span><span class="p">)</span> <span class="kn">from</span><span class="w"> </span><span class="kc">None</span>  <span class="c1"># &lt;- not caught in the next clause</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;never&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">4</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">ValueError</span>: <span class="n">2</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>Raising a new instance of a naked exception does not cause this exception to
be wrapped by an exception group. Rather, the exception is raised as is, and
if it needs to be combined with other propagated exceptions, it becomes a
direct child of the new exception group created for that:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;a&#39;</span><span class="p">)])</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;x&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">  | ExceptionGroup:  (1 sub-exception)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: eg (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | ValueError: a</span>
<span class="go">      +------------------------------------</span>
<span class="go">    |</span>
<span class="go">    | During handling of the above exception, another exception occurred:</span>
<span class="go">    |</span>
<span class="go">    | Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 4, in &lt;module&gt;</span>
<span class="go">    | KeyError: &#39;x&#39;</span>
<span class="go">    +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;a&#39;</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s1">&#39;b&#39;</span><span class="p">)])</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">KeyError</span><span class="p">(</span><span class="s1">&#39;x&#39;</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">  | ExceptionGroup:  (2 sub-exceptions)</span>
<span class="go">  +-+---------------- 1 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: eg (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | ValueError: a</span>
<span class="go">      +------------------------------------</span>
<span class="go">    |</span>
<span class="go">    | During handling of the above exception, another exception occurred:</span>
<span class="go">    |</span>
<span class="go">    | Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 4, in &lt;module&gt;</span>
<span class="go">    | KeyError: &#39;x&#39;</span>
<span class="go">    +---------------- 2 ----------------</span>
<span class="go">    | Exception Group Traceback (most recent call last):</span>
<span class="go">    |   File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt;</span>
<span class="go">    | ExceptionGroup: eg (1 sub-exception)</span>
<span class="go">    +-+---------------- 1 ----------------</span>
<span class="go">      | TypeError: b</span>
<span class="go">      +------------------------------------</span>
<span class="gp">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>Finally, as an example of how the proposed semantics can help us work
effectively with exception groups, the following code ignores all <code class="docutils literal notranslate"><span class="pre">EPIPE</span></code>
OS errors, while letting all other exceptions propagate.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">low_level_os_operation</span><span class="p">()</span>
<span class="k">except</span><span class="o">*</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">errors</span><span class="p">:</span>
    <span class="n">exc</span> <span class="o">=</span> <span class="n">errors</span><span class="o">.</span><span class="n">subgroup</span><span class="p">(</span><span class="k">lambda</span> <span class="n">e</span><span class="p">:</span> <span class="n">e</span><span class="o">.</span><span class="n">errno</span> <span class="o">!=</span> <span class="n">errno</span><span class="o">.</span><span class="n">EPIPE</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">exc</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span>
        <span class="k">raise</span> <span class="n">exc</span> <span class="kn">from</span><span class="w"> </span><span class="kc">None</span>
</pre></div>
</div>
</section>
<section id="caught-exception-objects">
<h4><a class="toc-backref" href="#caught-exception-objects" role="doc-backlink">Caught Exception Objects</a></h4>
<p>It is important to point out that the exception group bound to <code class="docutils literal notranslate"><span class="pre">e</span></code> in an
<code class="docutils literal notranslate"><span class="pre">except*</span></code> clause is an ephemeral object. Raising it via <code class="docutils literal notranslate"><span class="pre">raise</span></code> or
<code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">e</span></code> will not cause changes to the overall shape of the original
exception group.  Any modifications to <code class="docutils literal notranslate"><span class="pre">e</span></code> will likely be lost:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span> <span class="o">=</span> <span class="n">ExceptionGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">TypeError</span><span class="p">(</span><span class="mi">12</span><span class="p">)])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span><span class="o">.</span><span class="n">foo</span> <span class="o">=</span> <span class="s1">&#39;foo&#39;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="n">eg</span>
<span class="gp">... </span><span class="k">except</span><span class="o">*</span> <span class="ne">TypeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="n">e</span><span class="o">.</span><span class="n">foo</span> <span class="o">=</span> <span class="s1">&#39;bar&#39;</span>
<span class="gp">... </span><span class="c1">#   ^----------- ``e`` is an ephemeral object that might get</span>
<span class="gp">&gt;&gt;&gt; </span><span class="c1">#                      destroyed after the ``except*`` clause.</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">eg</span><span class="o">.</span><span class="n">foo</span>
<span class="go">&#39;foo&#39;</span>
</pre></div>
</div>
</section>
<section id="forbidden-combinations">
<h4><a class="toc-backref" href="#forbidden-combinations" role="doc-backlink">Forbidden Combinations</a></h4>
<p>It is not possible to use both traditional <code class="docutils literal notranslate"><span class="pre">except</span></code> blocks and the new
<code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses in the same <code class="docutils literal notranslate"><span class="pre">try</span></code> statement. The following is a
<code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code>:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="k">pass</span>
<span class="k">except</span><span class="o">*</span> <span class="n">CancelledError</span><span class="p">:</span>  <span class="c1"># &lt;- SyntaxError:</span>
    <span class="k">pass</span>                 <span class="c1">#    combining ``except`` and ``except*``</span>
                         <span class="c1">#    is prohibited</span>
</pre></div>
</div>
<p>It is possible to catch the <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> and <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code>
types with <code class="docutils literal notranslate"><span class="pre">except</span></code>, but not with <code class="docutils literal notranslate"><span class="pre">except*</span></code> because the latter is
ambiguous:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">ExceptionGroup</span><span class="p">:</span>  <span class="c1"># &lt;- This works</span>
    <span class="k">pass</span>

<span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span> <span class="n">ExceptionGroup</span><span class="p">:</span>  <span class="c1"># &lt;- Runtime error</span>
    <span class="k">pass</span>

<span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span> <span class="p">(</span><span class="ne">TypeError</span><span class="p">,</span> <span class="n">ExceptionGroup</span><span class="p">):</span>  <span class="c1"># &lt;- Runtime error</span>
    <span class="k">pass</span>
</pre></div>
</div>
<p>An empty “match anything” <code class="docutils literal notranslate"><span class="pre">except*</span></code> block is not supported as its meaning may
be confusing:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span><span class="o">*</span><span class="p">:</span>   <span class="c1"># &lt;- SyntaxError</span>
    <span class="k">pass</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">continue</span></code>, <code class="docutils literal notranslate"><span class="pre">break</span></code>, and <code class="docutils literal notranslate"><span class="pre">return</span></code> are disallowed in <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses,
causing a <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code>. This is because the exceptions in an
<code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> are assumed to be independent, and the presence or absence
of one of them should not impact handling of the others, as could happen if we
allow an <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause to change the way control flows through other
clauses.</p>
</section>
</section>
</section>
<section id="backwards-compatibility">
<h2><a class="toc-backref" href="#backwards-compatibility" role="doc-backlink">Backwards Compatibility</a></h2>
<p>Backwards compatibility was a requirement of our design, and the changes we
propose in this PEP will not break any existing code:</p>
<ul class="simple">
<li>The addition of the new builtin exception types <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> and
<code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> does not impact existing programs. The way that
existing exceptions are handled and displayed does not change in any way.</li>
<li>The behaviour of <code class="docutils literal notranslate"><span class="pre">except</span></code> is unchanged so existing code will continue to work.
Programs will only be impacted by the changes proposed in this PEP once they
begin to use exception groups and <code class="docutils literal notranslate"><span class="pre">except*</span></code>.</li>
<li>An important concern was that <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception:</span></code> will continue to catch
almost all exceptions, and by making <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> extend <code class="docutils literal notranslate"><span class="pre">Exception</span></code>
we ensured that this will be the case.  <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroups</span></code> will not be
caught, which is appropriate because they include exceptions that would not
have been caught by <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception</span></code>.</li>
</ul>
<p>Once programs begin to use these features, there will be migration issues to
consider:</p>
<ul class="simple">
<li>An <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">T:</span></code> clause that wraps code which is now potentially raising
an exception group may need to become <code class="docutils literal notranslate"><span class="pre">except*</span> <span class="pre">T:</span></code>, and its body may
need to be updated. This means that raising an exception group is an
API-breaking change and will likely be done in new APIs rather than
added to existing ones.</li>
<li>Libraries that need to support older Python versions will not be able to use
<code class="docutils literal notranslate"><span class="pre">except*</span></code> or raise exception groups.</li>
</ul>
</section>
<section id="how-to-teach-this">
<h2><a class="toc-backref" href="#how-to-teach-this" role="doc-backlink">How to Teach This</a></h2>
<p>Exception groups and <code class="docutils literal notranslate"><span class="pre">except*</span></code> will be documented as part of the language
standard. Libraries that raise exception groups such as <code class="docutils literal notranslate"><span class="pre">asyncio</span></code> will need
to specify this in their documentation and clarify which API calls need to be
wrapped with <code class="docutils literal notranslate"><span class="pre">try-except*</span></code> rather than <code class="docutils literal notranslate"><span class="pre">try-except</span></code>.</p>
</section>
<section id="reference-implementation">
<h2><a class="toc-backref" href="#reference-implementation" role="doc-backlink">Reference Implementation</a></h2>
<p>We developed these concepts (and the examples for this PEP) with
the help of the reference implementation <a class="footnote-reference brackets" href="#id29" id="id14">[11]</a>.</p>
<p>It has the builtin <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> along with the changes to the traceback
formatting code, in addition to the grammar, compiler and interpreter changes
required to support <code class="docutils literal notranslate"><span class="pre">except*</span></code>. <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> will be added
soon.</p>
<p>Two opcodes were added: one implements the exception type match check via
<code class="docutils literal notranslate"><span class="pre">ExceptionGroup.split()</span></code>, and the other is used at the end of a <code class="docutils literal notranslate"><span class="pre">try-except</span></code>
construct to merge all unhandled, raised and reraised exceptions (if any).
The raised/reraised exceptions are collected in a list on the runtime stack.
For this purpose, the body of each <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause is wrapped in a traditional
<code class="docutils literal notranslate"><span class="pre">try-except</span></code> which captures any exceptions raised. Both raised and reraised
exceptions are collected in the same list. When the time comes to merge them
into a result, the raised and reraised exceptions are distinguished by comparing
their metadata fields (context, cause, traceback) with those of the originally
raised exception. As mentioned above, the reraised exceptions have the same
metadata as the original, while the raised ones do not.</p>
</section>
<section id="rejected-ideas">
<h2><a class="toc-backref" href="#rejected-ideas" role="doc-backlink">Rejected Ideas</a></h2>
<section id="make-exception-groups-iterable">
<h3><a class="toc-backref" href="#make-exception-groups-iterable" role="doc-backlink">Make Exception Groups Iterable</a></h3>
<p>We considered making exception groups iterable, so that <code class="docutils literal notranslate"><span class="pre">list(eg)</span></code> would
produce a flattened list of the leaf exceptions contained in the group.
We decided that this would not be a sound API, because the metadata
(cause, context and traceback) of the individual exceptions in a group is
incomplete and this could create problems.</p>
<p>Furthermore, as we explained in the <a class="reference internal" href="#handling-exception-groups">Handling Exception Groups</a> section, we
find it unlikely that iteration over leaf exceptions will have many use cases.
We did, however, provide there the code for a traversal algorithm that
correctly constructs each leaf exceptions’ metadata. If it does turn out to
be useful in practice, we can in the future add that utility to the standard
library or even make exception groups iterable.</p>
</section>
<section id="make-exceptiongroup-extend-baseexception">
<h3><a class="toc-backref" href="#make-exceptiongroup-extend-baseexception" role="doc-backlink">Make <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> Extend <code class="docutils literal notranslate"><span class="pre">BaseException</span></code></a></h3>
<p>We considered making <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> subclass only <code class="docutils literal notranslate"><span class="pre">BaseException</span></code>,
and not <code class="docutils literal notranslate"><span class="pre">Exception</span></code>. The rationale of this was that we expect exception
groups to be used in a deliberate manner where they are needed, and raised
only by APIs that are specifically designed and documented to do so. In
this context, an <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> escaping from an API that is not
intended to raise one is a bug, and we wanted to give it “fatal error”
status so that <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception</span></code> will not inadvertently swallow it.
This would have been consistent with the way <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">T:</span></code> does not catch
exception groups that contain <code class="docutils literal notranslate"><span class="pre">T</span></code> for all other types, and would help
contain <code class="docutils literal notranslate"><span class="pre">ExceptionGroups</span></code> to the parts of the program in which they are
supposed to appear. However, it was clear from the public discussion that
<code class="docutils literal notranslate"><span class="pre">T=Exception</span></code> is a special case, and there are developers who feel strongly
that <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception:</span></code> should catch “almost everything”, including
exception groups. This is why we decided to make <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> a
subclass of <code class="docutils literal notranslate"><span class="pre">Exception</span></code>.</p>
</section>
<section id="make-it-impossible-to-wrap-baseexceptions-in-an-exception-group">
<h3><a class="toc-backref" href="#make-it-impossible-to-wrap-baseexceptions-in-an-exception-group" role="doc-backlink">Make it Impossible to Wrap <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code> in an Exception Group</a></h3>
<p>A consequence of the decision to make <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> extend
<code class="docutils literal notranslate"><span class="pre">Exception</span></code> is that <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> should not wrap <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code>
like <code class="docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code>, as they are not currently caught by
<code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception:</span></code>. We considered the option of simply making it
impossible to wrap <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code>, but eventually decided to make
it possible through the <code class="docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code> type, which extends
<code class="docutils literal notranslate"><span class="pre">BaseException</span></code> rather than <code class="docutils literal notranslate"><span class="pre">Exception</span></code>.  Making this possible
adds flexibility to the language and leaves it for the programmer to
weigh the benefit of wrapping <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code> rather than propagating
them in their naked form while discarding any other exceptions.</p>
</section>
<section id="traceback-representation">
<h3><a class="toc-backref" href="#traceback-representation" role="doc-backlink">Traceback Representation</a></h3>
<p>We considered options for adapting the traceback data structure to represent
trees, but it became apparent that a traceback tree is not meaningful once
separated from the exceptions it refers to. While a simple-path traceback can
be attached to any exception by a <code class="docutils literal notranslate"><span class="pre">with_traceback()</span></code> call, it is hard to
imagine a case where it makes sense to assign a traceback tree to an exception
group.  Furthermore, a useful display of the traceback includes information
about the nested exceptions. For these reasons we decided that it is best to
leave the traceback mechanism as it is and modify the traceback display code.</p>
</section>
<section id="extend-except-to-handle-exception-groups">
<h3><a class="toc-backref" href="#extend-except-to-handle-exception-groups" role="doc-backlink">Extend <code class="docutils literal notranslate"><span class="pre">except</span></code> to Handle Exception Groups</a></h3>
<p>We considered extending the semantics of <code class="docutils literal notranslate"><span class="pre">except</span></code> to handle
exception groups, instead of introducing <code class="docutils literal notranslate"><span class="pre">except*</span></code>. There were two
backwards compatibility concerns with this. The first is the type of the
caught exception. Consider this example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">.</span> <span class="o">.</span> <span class="o">.</span>
<span class="k">except</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">if</span> <span class="n">err</span><span class="o">.</span><span class="n">errno</span> <span class="o">!=</span> <span class="n">ENOENT</span><span class="p">:</span>
        <span class="k">raise</span>
</pre></div>
</div>
<p>If the value assigned to err is an exception group containing all of
the <code class="docutils literal notranslate"><span class="pre">OSErrors</span></code> that were raised, then the attribute access <code class="docutils literal notranslate"><span class="pre">err.errno</span></code>
no longer works. So we would need to execute the body of the <code class="docutils literal notranslate"><span class="pre">except</span></code>
clause multiple times, once for each exception in the group. However, this
too is a potentially breaking change because at the moment we write <code class="docutils literal notranslate"><span class="pre">except</span></code>
clauses with the knowledge that they are only executed once. If there is
a non-idempotent operation there, such as releasing a resource, the
repetition could be harmful.</p>
<p>The idea of making <code class="docutils literal notranslate"><span class="pre">except</span></code> iterate over the leaf exceptions of an exception
group is at the heart of an <a class="reference external" href="https://discuss.python.org/t/flat-exception-groups-alternative-to-pep-654/10433">alternative proposal to this PEP by Nathaniel J. Smith</a>,
and the discussion about that proposal further elaborates on the pitfalls of
changing <code class="docutils literal notranslate"><span class="pre">except</span></code> semantics in a mature language like Python, as well as
deviating from the semantics that parallel constructs have in other languages.</p>
<p>Another option that came up in the public discussion was to add <code class="docutils literal notranslate"><span class="pre">except*</span></code>,
but also make <code class="docutils literal notranslate"><span class="pre">except</span></code> treat <code class="docutils literal notranslate"><span class="pre">ExceptionGroups</span></code> as a special case.
<code class="docutils literal notranslate"><span class="pre">except</span></code> would then do something along the lines of extracting one exception
of matching type from the group in order to handle it (while discarding all
the other exceptions in the group). The motivation behind
these suggestions was to make the adoption of exception groups safer, in that
<code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">T</span></code> catches <code class="docutils literal notranslate"><span class="pre">Ts</span></code> that are wrapped in exception groups. We decided
that such an approach adds considerable complexity to the semantics of the
language without making it more powerful. Even if it would make the adoption
of exception groups slightly easier (which is not at all obvious), these are
not the semantics we would like to have in the long term.</p>
</section>
<section id="a-new-except-alternative">
<h3><a class="toc-backref" href="#a-new-except-alternative" role="doc-backlink">A New <code class="docutils literal notranslate"><span class="pre">except</span></code> Alternative</a></h3>
<p>We considered introducing a new keyword (such as <code class="docutils literal notranslate"><span class="pre">catch</span></code>) which can be used
to handle both naked exceptions and exception groups. Its semantics would
be the same as those of <code class="docutils literal notranslate"><span class="pre">except*</span></code> when catching an exception group, but
it would not wrap a naked exception to create an exception group. This
would have been part of a long term plan to replace <code class="docutils literal notranslate"><span class="pre">except</span></code> by <code class="docutils literal notranslate"><span class="pre">catch</span></code>,
but we decided that deprecating <code class="docutils literal notranslate"><span class="pre">except</span></code> in favour of an enhanced keyword
would be too confusing for users at this time, so it is more appropriate
to introduce the <code class="docutils literal notranslate"><span class="pre">except*</span></code> syntax for exception groups while <code class="docutils literal notranslate"><span class="pre">except</span></code>
continues to be used for simple exceptions.</p>
</section>
<section id="applying-an-except-clause-on-one-exception-at-a-time">
<h3><a class="toc-backref" href="#applying-an-except-clause-on-one-exception-at-a-time" role="doc-backlink">Applying an <code class="docutils literal notranslate"><span class="pre">except*</span></code> Clause on One Exception at a Time</a></h3>
<p>We explained above that it is unsafe to execute an <code class="docutils literal notranslate"><span class="pre">except</span></code> clause in
existing code more than once, because the code may not be idempotent.
We considered doing this in the new <code class="docutils literal notranslate"><span class="pre">except*</span></code> clauses,
where the backwards compatibility considerations do not exist.
The idea is to always execute an <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause on a single exception,
possibly executing the same clause multiple times when it matches multiple
exceptions. We decided instead to execute each <code class="docutils literal notranslate"><span class="pre">except*</span></code> clause at most
once, giving it an exception group that contains all matching exceptions. The
reason for this decision was the observation that when a program needs to know
the particular context of an exception it is handling, the exception is
handled before it is grouped and raised together with other exceptions.</p>
<p>For example, <code class="docutils literal notranslate"><span class="pre">KeyError</span></code> is an exception that typically relates to a certain
operation. Any recovery code would be local to the place where the error
occurred, and would use the traditional <code class="docutils literal notranslate"><span class="pre">except</span></code>:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">dct</span><span class="p">[</span><span class="n">key</span><span class="p">]</span>
<span class="k">except</span> <span class="ne">KeyError</span><span class="p">:</span>
    <span class="c1"># handle the exception</span>
</pre></div>
</div>
<p>It is unlikely that asyncio users would want to do something like this:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="k">async</span> <span class="k">with</span> <span class="n">asyncio</span><span class="o">.</span><span class="n">TaskGroup</span><span class="p">()</span> <span class="k">as</span> <span class="n">g</span><span class="p">:</span>
        <span class="n">g</span><span class="o">.</span><span class="n">create_task</span><span class="p">(</span><span class="n">task1</span><span class="p">);</span> <span class="n">g</span><span class="o">.</span><span class="n">create_task</span><span class="p">(</span><span class="n">task2</span><span class="p">)</span>
<span class="k">except</span><span class="o">*</span> <span class="ne">KeyError</span><span class="p">:</span>
    <span class="c1"># handling KeyError here is meaningless, there&#39;s</span>
    <span class="c1"># no context to do anything with it but to log it.</span>
</pre></div>
</div>
<p>When a program handles a collection of exceptions that were aggregated into
an exception group, it would not typically attempt to recover from any
particular failed operation, but will rather use the types of the errors to
determine how they should impact the program’s control flow or what logging
or cleanup is required. This decision is likely to be the same whether the group
contains a single or multiple instances of something like a <code class="docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code>
or <code class="docutils literal notranslate"><span class="pre">asyncio.CancelledError</span></code>.  Therefore, it is more convenient to handle all
exceptions matching an <code class="docutils literal notranslate"><span class="pre">except*</span></code> at once.  If it does turn out to be necessary,
the handler can inpect the exception group and process the individual
exceptions in it.</p>
</section>
<section id="not-matching-naked-exceptions-in-except">
<h3><a class="toc-backref" href="#not-matching-naked-exceptions-in-except" role="doc-backlink">Not Matching Naked Exceptions in <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></h3>
<p>We considered the option of making <code class="docutils literal notranslate"><span class="pre">except*</span> <span class="pre">T</span></code> match only exception groups
that contain <code class="docutils literal notranslate"><span class="pre">Ts</span></code>, but not naked <code class="docutils literal notranslate"><span class="pre">Ts</span></code>. To see why we thought this would
not be a desirable feature, return to the distinction in the previous paragraph
between operation errors and control flow exceptions. If we don’t know whether
we should expect naked exceptions or exception groups from the body of a
<code class="docutils literal notranslate"><span class="pre">try</span></code> block,  then we’re not in the position of handling operation errors.
Rather, we are likely calling a fairly generic function and will be handling
errors to make control flow decisions. We are likely to do the same thing
whether we catch a naked exception of type <code class="docutils literal notranslate"><span class="pre">T</span></code> or an exception group
with one or more <code class="docutils literal notranslate"><span class="pre">Ts</span></code>. Therefore, the burden of having to explicitly handle
both is not likely to have semantic benefit.</p>
<p>If it does turn out to be necessary to make the distinction, it is always
possible to nest in the <code class="docutils literal notranslate"><span class="pre">try-except*</span></code> clause an additional <code class="docutils literal notranslate"><span class="pre">try-except</span></code>
clause which intercepts and handles a naked exception before the <code class="docutils literal notranslate"><span class="pre">except*</span></code>
clause has a chance to wrap it in an  exception group. In this case the
overhead of specifying both is not additional burden - we really do need to
write a separate code block to handle each case:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="o">...</span>
    <span class="k">except</span> <span class="n">SomeError</span><span class="p">:</span>
        <span class="c1"># handle the naked exception</span>
<span class="k">except</span><span class="o">*</span> <span class="n">SomeError</span><span class="p">:</span>
    <span class="c1"># handle the exception group</span>
</pre></div>
</div>
</section>
<section id="allow-mixing-except-and-except-in-the-same-try">
<h3><a class="toc-backref" href="#allow-mixing-except-and-except-in-the-same-try" role="doc-backlink">Allow mixing <code class="docutils literal notranslate"><span class="pre">except:</span></code> and <code class="docutils literal notranslate"><span class="pre">except*:</span></code> in the same <code class="docutils literal notranslate"><span class="pre">try</span></code></a></h3>
<p>This option was rejected because it adds complexity without adding useful
semantics. Presumably the intention would be that an <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">T:</span></code> block handles
only naked exceptions of type <code class="docutils literal notranslate"><span class="pre">T</span></code>, while <code class="docutils literal notranslate"><span class="pre">except*</span> <span class="pre">T:</span></code> handles <code class="docutils literal notranslate"><span class="pre">T</span></code> in
exception groups. We already discussed above why this is unlikely
to be useful in practice, and if it is needed then the nested <code class="docutils literal notranslate"><span class="pre">try-except</span></code>
block can be used instead to achieve the same result.</p>
</section>
<section id="try-instead-of-except">
<h3><a class="toc-backref" href="#try-instead-of-except" role="doc-backlink"><code class="docutils literal notranslate"><span class="pre">try*</span></code> instead of <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></h3>
<p>Since either all or none of the clauses of a <code class="docutils literal notranslate"><span class="pre">try</span></code> construct are <code class="docutils literal notranslate"><span class="pre">except*</span></code>,
we considered changing the syntax of the <code class="docutils literal notranslate"><span class="pre">try</span></code> instead of all the <code class="docutils literal notranslate"><span class="pre">except*</span></code>
clauses. We rejected this because it would be less obvious. The fact that we
are handling exception groups of <code class="docutils literal notranslate"><span class="pre">T</span></code> rather than only naked <code class="docutils literal notranslate"><span class="pre">Ts</span></code> should be
specified in the same place where we state <code class="docutils literal notranslate"><span class="pre">T</span></code>.</p>
</section>
<section id="alternative-syntax-options">
<h3><a class="toc-backref" href="#alternative-syntax-options" role="doc-backlink">Alternative syntax options</a></h3>
<p>Alternatives to the <code class="docutils literal notranslate"><span class="pre">except*</span></code> syntax were evaluated in a <a class="reference external" href="http://groups.google.com/g/dev-python/c/G3p9_jovyus">discussion on python-dev</a>, and it was suggested to use
<code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">group</span></code>. Upon careful evaluation this was rejected because the following
would be ambiguous, as it is currently valid syntax where <code class="docutils literal notranslate"><span class="pre">group</span></code> is interpreted
as a callable. The same is true for any valid identifier.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
   <span class="o">...</span>
<span class="k">except</span> <span class="n">group</span> <span class="p">(</span><span class="n">T1</span><span class="p">,</span> <span class="n">T2</span><span class="p">):</span>
   <span class="o">...</span>
</pre></div>
</div>
</section>
</section>
<section id="programming-without-except">
<h2><a class="toc-backref" href="#programming-without-except" role="doc-backlink">Programming Without ‘except *’</a></h2>
<p>Consider the following simple example of the <code class="docutils literal notranslate"><span class="pre">except*</span></code> syntax (pretending
Trio natively supported this proposal):</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="k">async</span> <span class="k">with</span> <span class="n">trio</span><span class="o">.</span><span class="n">open_nursery</span><span class="p">()</span> <span class="k">as</span> <span class="n">nursery</span><span class="p">:</span>
        <span class="c1"># Make two concurrent calls to child()</span>
        <span class="n">nursery</span><span class="o">.</span><span class="n">start_soon</span><span class="p">(</span><span class="n">child</span><span class="p">)</span>
        <span class="n">nursery</span><span class="o">.</span><span class="n">start_soon</span><span class="p">(</span><span class="n">child</span><span class="p">)</span>
<span class="k">except</span><span class="o">*</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="k">pass</span>
</pre></div>
</div>
<p>Here is how this code would look in Python 3.9:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span><span class="w"> </span><span class="nf">handle_ValueError</span><span class="p">(</span><span class="n">exc</span><span class="p">):</span>
    <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">exc</span><span class="p">,</span> <span class="ne">ValueError</span><span class="p">):</span>
        <span class="k">return</span> <span class="kc">None</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">exc</span>   <span class="c1"># reraise exc</span>

<span class="k">with</span> <span class="n">MultiError</span><span class="o">.</span><span class="n">catch</span><span class="p">(</span><span class="n">handle_ValueError</span><span class="p">):</span>
    <span class="k">async</span> <span class="k">with</span> <span class="n">trio</span><span class="o">.</span><span class="n">open_nursery</span><span class="p">()</span> <span class="k">as</span> <span class="n">nursery</span><span class="p">:</span>
        <span class="c1"># Make two concurrent calls to child()</span>
        <span class="n">nursery</span><span class="o">.</span><span class="n">start_soon</span><span class="p">(</span><span class="n">child</span><span class="p">)</span>
        <span class="n">nursery</span><span class="o">.</span><span class="n">start_soon</span><span class="p">(</span><span class="n">child</span><span class="p">)</span>
</pre></div>
</div>
<p>This example clearly demonstrates how unintuitive and cumbersome handling
of multiple errors is in current Python.  The exception handling logic has
to be in a separate closure and is fairly low level, requiring the writer to
have non-trivial understanding of both Python exceptions mechanics and the
Trio APIs.  Instead of using the <code class="docutils literal notranslate"><span class="pre">try..except</span></code> block we have to use a
<code class="docutils literal notranslate"><span class="pre">with</span></code> block.  We need to explicitly reraise exceptions we are not handling.
Handling more exception types or implementing more complex
exception handling logic will only further complicate the code to the point
of it being unreadable.</p>
</section>
<section id="see-also">
<h2><a class="toc-backref" href="#see-also" role="doc-backlink">See Also</a></h2>
<ul class="simple">
<li>An analysis of how exception groups will likely be used in asyncio
programs: <a class="footnote-reference brackets" href="#id28" id="id15">[10]</a>.</li>
<li>The issue where the <code class="docutils literal notranslate"><span class="pre">except*</span></code> concept was first formalized: <a class="footnote-reference brackets" href="#id30" id="id16">[12]</a>.</li>
<li><code class="docutils literal notranslate"><span class="pre">MultiError2</span></code> design document: <a class="footnote-reference brackets" href="#id21" id="id17">[3]</a>.</li>
<li>Reporting Multiple Errors in the Hypothesis library: <a class="footnote-reference brackets" href="#id25" id="id18">[7]</a>.</li>
</ul>
</section>
<section id="acknowledgements">
<h2><a class="toc-backref" href="#acknowledgements" role="doc-backlink">Acknowledgements</a></h2>
<p>We wish to thank Nathaniel J. Smith and the other Trio developers for their
work on structured concurrency. We borrowed the idea of constructing an
exception tree whose nodes are exceptions from MultiError, and the <code class="docutils literal notranslate"><span class="pre">split()</span></code>
API from the design document for MultiError V2.  The discussions on python-dev
and elsewhere helped us improve upon the first draft of the PEP in multiple
ways, both the design and the exposition. For this we appreciate all those who
contributed ideas and asked good questions:  Ammar Askar, Matthew Barnett,
Ran Benita, Emily Bowman, Brandt Bucher, Joao Bueno, Baptiste Carvello,
Rob Cliffe, Alyssa Coghlan, Steven D’Aprano, Caleb Donovick, Steve Dower,
Greg Ewing, Ethan Furman, Pablo Salgado, Jonathan Goble, Joe Gottman, Thomas Grainger,
Larry Hastings, Zac Hatfield-Dodds, Chris Jerdonek, Jim Jewett, Sven Kunze,
Łukasz Langa, Glenn Linderman, Paul Moore, Antoine Pitrou, Ivan Pozdeev,
Patrick Reader, Terry Reedy, Sascha Schlemmer, Barry Scott, Mark Shannon,
Damian Shaw, Cameron Simpson, Gregory Smith, Paul Sokolovsky, Calvin Spealman,
Steve Stagg, Victor Stinner, Marco Sulla, Petr Viktorin and Barry Warsaw.</p>
</section>
<section id="acceptance">
<h2><a class="toc-backref" href="#acceptance" role="doc-backlink">Acceptance</a></h2>
<p><a class="pep reference internal" href="../pep-0654/" title="PEP 654 – Exception Groups and except*">PEP 654</a> was <a class="reference external" href="http://discuss.python.org/t/accepting-pep-654-exception-groups-and-except/10813">accepted by Thomas Wouters on Sep 24, 2021</a>.</p>
</section>
<section id="references">
<h2><a class="toc-backref" href="#references" role="doc-backlink">References</a></h2>
<aside class="footnote-list brackets">
<aside class="footnote brackets" id="id19" role="doc-footnote">
<dt class="label" id="id19">[<a href="#id1">1</a>]</dt>
<dd><a class="reference external" href="https://docs.python.org/3/library/asyncio-task.html#asyncio.gather">https://docs.python.org/3/library/asyncio-task.html#asyncio.gather</a></aside>
<aside class="footnote brackets" id="id20" role="doc-footnote">
<dt class="label" id="id20">[2]<em> (<a href='#id2'>1</a>, <a href='#id11'>2</a>) </em></dt>
<dd><a class="reference external" href="https://trio.readthedocs.io/en/stable/">https://trio.readthedocs.io/en/stable/</a></aside>
<aside class="footnote brackets" id="id21" role="doc-footnote">
<dt class="label" id="id21">[3]<em> (<a href='#id4'>1</a>, <a href='#id17'>2</a>) </em></dt>
<dd><a class="reference external" href="https://github.com/python-trio/trio/issues/611">https://github.com/python-trio/trio/issues/611</a></aside>
<aside class="footnote brackets" id="id22" role="doc-footnote">
<dt class="label" id="id22">[<a href="#id6">4</a>]</dt>
<dd><a class="reference external" href="https://github.com/python/cpython/issues/74166">https://github.com/python/cpython/issues/74166</a></aside>
<aside class="footnote brackets" id="id23" role="doc-footnote">
<dt class="label" id="id23">[<a href="#id7">5</a>]</dt>
<dd><a class="reference external" href="https://docs.python.org/3/library/atexit.html#atexit.register">https://docs.python.org/3/library/atexit.html#atexit.register</a></aside>
<aside class="footnote brackets" id="id24" role="doc-footnote">
<dt class="label" id="id24">[<a href="#id8">6</a>]</dt>
<dd><a class="reference external" href="https://github.com/pytest-dev/pytest/issues/8217">https://github.com/pytest-dev/pytest/issues/8217</a></aside>
<aside class="footnote brackets" id="id25" role="doc-footnote">
<dt class="label" id="id25">[7]<em> (<a href='#id9'>1</a>, <a href='#id18'>2</a>) </em></dt>
<dd><a class="reference external" href="https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.report_multiple_bugs">https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.report_multiple_bugs</a></aside>
<aside class="footnote brackets" id="id26" role="doc-footnote">
<dt class="label" id="id26">[<a href="#id10">8</a>]</dt>
<dd><a class="reference external" href="https://github.com/python/cpython/issues/85034">https://github.com/python/cpython/issues/85034</a></aside>
<aside class="footnote brackets" id="id27" role="doc-footnote">
<dt class="label" id="id27">[9]<em> (<a href='#id3'>1</a>, <a href='#id12'>2</a>) </em></dt>
<dd><a class="reference external" href="https://trio.readthedocs.io/en/stable/reference-core.html#trio.MultiError">https://trio.readthedocs.io/en/stable/reference-core.html#trio.MultiError</a></aside>
<aside class="footnote brackets" id="id28" role="doc-footnote">
<dt class="label" id="id28">[10]<em> (<a href='#id13'>1</a>, <a href='#id15'>2</a>) </em></dt>
<dd><a class="reference external" href="https://github.com/python/exceptiongroups/issues/3#issuecomment-716203284">https://github.com/python/exceptiongroups/issues/3#issuecomment-716203284</a></aside>
<aside class="footnote brackets" id="id29" role="doc-footnote">
<dt class="label" id="id29">[<a href="#id14">11</a>]</dt>
<dd><a class="reference external" href="https://github.com/iritkatriel/cpython/tree/exceptionGroup-stage5">https://github.com/iritkatriel/cpython/tree/exceptionGroup-stage5</a></aside>
<aside class="footnote brackets" id="id30" role="doc-footnote">
<dt class="label" id="id30">[<a href="#id16">12</a>]</dt>
<dd><a class="reference external" href="https://github.com/python/exceptiongroups/issues/4">https://github.com/python/exceptiongroups/issues/4</a></aside>
<aside class="footnote brackets" id="id31" role="doc-footnote">
<dt class="label" id="id31">[<a href="#id5">13</a>]</dt>
<dd><a class="reference external" href="https://trio.readthedocs.io/en/stable/reference-core.html#nurseries-and-spawning">https://trio.readthedocs.io/en/stable/reference-core.html#nurseries-and-spawning</a></aside>
</aside>
</section>
<section id="copyright">
<h2><a class="toc-backref" href="#copyright" role="doc-backlink">Copyright</a></h2>
<p>This document is placed in the public domain or under the
CC0-1.0-Universal license, whichever is more permissive.</p>
</section>
</section>
<hr class="docutils" />
<p>Source: <a class="reference external" href="https://github.com/python/peps/blob/main/peps/pep-0654.rst">https://github.com/python/peps/blob/main/peps/pep-0654.rst</a></p>
<p>Last modified: <a class="reference external" href="https://github.com/python/peps/commits/main/peps/pep-0654.rst">2025-02-01 08:55:40 GMT</a></p>

        </article>
        <nav id="pep-sidebar">
            <h2>Contents</h2>
            <ul>
<li><a class="reference internal" href="#abstract">Abstract</a></li>
<li><a class="reference internal" href="#motivation">Motivation</a></li>
<li><a class="reference internal" href="#rationale">Rationale</a></li>
<li><a class="reference internal" href="#specification">Specification</a><ul>
<li><a class="reference internal" href="#exceptiongroup-and-baseexceptiongroup">ExceptionGroup and BaseExceptionGroup</a><ul>
<li><a class="reference internal" href="#subclassing-exception-groups">Subclassing Exception Groups</a></li>
<li><a class="reference internal" href="#the-traceback-of-an-exception-group">The Traceback of an Exception Group</a></li>
<li><a class="reference internal" href="#handling-exception-groups">Handling Exception Groups</a></li>
</ul>
</li>
<li><a class="reference internal" href="#except">except*</a><ul>
<li><a class="reference internal" href="#recursive-matching">Recursive Matching</a></li>
<li><a class="reference internal" href="#unmatched-exceptions">Unmatched Exceptions</a></li>
<li><a class="reference internal" href="#naked-exceptions">Naked Exceptions</a></li>
<li><a class="reference internal" href="#raising-exceptions-in-an-except-block">Raising exceptions in an <code class="docutils literal notranslate"><span class="pre">except*</span></code> block</a></li>
<li><a class="reference internal" href="#chaining">Chaining</a></li>
<li><a class="reference internal" href="#raising-new-exceptions">Raising New Exceptions</a></li>
<li><a class="reference internal" href="#caught-exception-objects">Caught Exception Objects</a></li>
<li><a class="reference internal" href="#forbidden-combinations">Forbidden Combinations</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="reference internal" href="#backwards-compatibility">Backwards Compatibility</a></li>
<li><a class="reference internal" href="#how-to-teach-this">How to Teach This</a></li>
<li><a class="reference internal" href="#reference-implementation">Reference Implementation</a></li>
<li><a class="reference internal" href="#rejected-ideas">Rejected Ideas</a><ul>
<li><a class="reference internal" href="#make-exception-groups-iterable">Make Exception Groups Iterable</a></li>
<li><a class="reference internal" href="#make-exceptiongroup-extend-baseexception">Make <code class="docutils literal notranslate"><span class="pre">ExceptionGroup</span></code> Extend <code class="docutils literal notranslate"><span class="pre">BaseException</span></code></a></li>
<li><a class="reference internal" href="#make-it-impossible-to-wrap-baseexceptions-in-an-exception-group">Make it Impossible to Wrap <code class="docutils literal notranslate"><span class="pre">BaseExceptions</span></code> in an Exception Group</a></li>
<li><a class="reference internal" href="#traceback-representation">Traceback Representation</a></li>
<li><a class="reference internal" href="#extend-except-to-handle-exception-groups">Extend <code class="docutils literal notranslate"><span class="pre">except</span></code> to Handle Exception Groups</a></li>
<li><a class="reference internal" href="#a-new-except-alternative">A New <code class="docutils literal notranslate"><span class="pre">except</span></code> Alternative</a></li>
<li><a class="reference internal" href="#applying-an-except-clause-on-one-exception-at-a-time">Applying an <code class="docutils literal notranslate"><span class="pre">except*</span></code> Clause on One Exception at a Time</a></li>
<li><a class="reference internal" href="#not-matching-naked-exceptions-in-except">Not Matching Naked Exceptions in <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></li>
<li><a class="reference internal" href="#allow-mixing-except-and-except-in-the-same-try">Allow mixing <code class="docutils literal notranslate"><span class="pre">except:</span></code> and <code class="docutils literal notranslate"><span class="pre">except*:</span></code> in the same <code class="docutils literal notranslate"><span class="pre">try</span></code></a></li>
<li><a class="reference internal" href="#try-instead-of-except"><code class="docutils literal notranslate"><span class="pre">try*</span></code> instead of <code class="docutils literal notranslate"><span class="pre">except*</span></code></a></li>
<li><a class="reference internal" href="#alternative-syntax-options">Alternative syntax options</a></li>
</ul>
</li>
<li><a class="reference internal" href="#programming-without-except">Programming Without ‘except *’</a></li>
<li><a class="reference internal" href="#see-also">See Also</a></li>
<li><a class="reference internal" href="#acknowledgements">Acknowledgements</a></li>
<li><a class="reference internal" href="#acceptance">Acceptance</a></li>
<li><a class="reference internal" href="#references">References</a></li>
<li><a class="reference internal" href="#copyright">Copyright</a></li>
</ul>

            <br>
            <a id="source" href="https://github.com/python/peps/blob/main/peps/pep-0654.rst?plain=1">Page Source (GitHub)</a>
        </nav>
    </section>
    <script src="../_static/colour_scheme.js"></script>
    <script src="../_static/wrap_tables.js"></script>
    <script src="../_static/sticky_banner.js"></script>
    <script src="https://analytics.python.org/js/script.outbound-links.js"
            data-domain="peps.python.org" defer></script>
</body>
</html>